### ISSUE TITLE
how to show multiple items selected of oi-select in edit mode

### ISSUE THREAD

**Issue by gsrgnagendra** [tamtakoe/oi.select#22]

**Comment by tamtakoe** [comment]
See http://tamtakoe.github.io/oi.select/#/select/#editableoptions
You can edit only last item. If you edit other item it will be the last.

**Comment by gsrgnagendra** [comment]
actually my problem is i have three values in my database table i want to show all the three should  be show selected  in  oi-select 
after retriving the data.so plz help me

**Comment by tamtakoe** [comment]
I understand that you are using the multiple option. And you want to have all the selected options in edit mode. This is not possible, because the editing mode characterizes oi-select element, but not your data. You can set `searchFilter` which will highlight the elements with fields `isEditable` for example.

Maybe I did not understand you correctly. Then attached a screenshot or example in plnker
